# NOTE: update this with your service name
service: notes-api

# Create an optimized package for our functions 
# By default, serverless Framework creates a singple package for all you lambda functions.
# This means that when a Lambda function is invoked, it will load all the code in your app,
# including all other Lambda funcitons. This negatively affects performance. The larger the Lambda
# function package is, the longer the cold starts.
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-west-2
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
